name: fabmws2025
channels:
  - conda-forge
dependencies:
  - cython
  - python-build
  - pip
  # compilation
  - gfortran != 15.1.*
  - netcdf-fortran
  - cmake
  - git
  - ninja
  # analysis
  - parsac
  # visualization
  - mpi4py
  - pyyaml
  - numpy
  - xarray
  - netcdf4
  - scipy
  - pyncview
  - awex
  - pygotm
  - matplotlib
  - cmocean
  - cartopy
  - proj
  - jupyterlab
  - ipympl
  - nc-time-axis
