#!/usr/bin/env bash

set -e

export CMAKE_GENERATOR=Ninja
export FC=gfortran

cmake -B build/gotm -S code/gotm -DFABM_BASE=code/fabm -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX}
cmake --build build/gotm --target install

set +e
