name: Install FABM workshop packages and test
on: push
jobs:
   main:
      strategy:
        fail-fast: false
        matrix:
          os: ["ubuntu-latest", "macos-13", "macos-latest", "windows-latest"]
          python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
      name: ${{ matrix.os }}-python-${{ matrix.python-version }}
      runs-on: ${{ matrix.os }}
      defaults:
        run:
          shell: ${{ matrix.os == 'windows-latest' && 'cmd /C call {0}' || 'bash -el {0}' }}
      env:
        CMAKE_GENERATOR: Ninja
        FC: gfortran
      steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: fabmws2025
      - name: Show conda package versions
        run: conda list
      - name: Show tool versions
        run: |
          gfortran --version
          cmake --version
          git --version
      - name: Build and install pyfabm
        run: pip install -v code/fabm
      - name: Build and install gotm (Windows)
        run: |
          cmake -B build/gotm -S code/gotm -DFABM_BASE=code/fabm -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_INSTALL_PREFIX=%CONDA_PREFIX%
          cmake --build build/gotm --target install
        if: matrix.os == 'windows-latest'
      - name: Build and install gotm (Linux, Mac)
        run: |
          cmake -B build/gotm -S code/gotm -DFABM_BASE=code/fabm -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX}
          cmake --build build/gotm --target install
        if: matrix.os != 'windows-latest'
      - name: Build and install pygetm (Windows)
        run: |
          cd code/pygetm
          install.bat
        if: matrix.os == 'windows-latest'
      - name: Build and install pygetm (Linux, Mac)
        run: |
          cd code/pygetm
          source ./install
        if: matrix.os != 'windows-latest'
      - name: Build and install fabmos
        run: pip install -v code/fabmos
      - name: Show versions
        run: |
          gotm --version
          python show_versions.py

